/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-09-03 10:31:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.format.DateTimeFormatter;
import java.util.List;
import com.entities.Contact;
import com.entities.User;
import com.dao.ContactLists;
import com.entities.User;

public final class contactList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1756810594956L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1756731695891L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.entities.Contact");
    _jspx_imports_classes.add("com.entities.User");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("com.dao.ContactLists");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Contact Management System || My Contacts</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100\">\r\n");
      out.write("	<div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<nav class=\"bg-blue-600 text-white shadow-lg\">\r\n");
      out.write("	<div class=\"max-w-7xl mx-auto px-4\">\r\n");
      out.write("		<div class=\"flex justify-between h-16\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Logo / Brand -->\r\n");
      out.write("			<div class=\"flex items-center\">\r\n");
      out.write("				<a href=\"/ContactManagementSystem\"\r\n");
      out.write("					class=\"text-xl font-bold tracking-wide\">Contact Mangement\r\n");
      out.write("					System</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Links -->\r\n");
      out.write("			<div class=\"hidden md:flex items-center space-x-6\">\r\n");
      out.write("				<a href=\"contactList.jsp\" class=\"hover:text-gray-200\">Contact\r\n");
      out.write("					List</a> <a href=\"AddContact.jsp\" class=\"hover:text-gray-200\">Add\r\n");
      out.write("					Contact</a>\r\n");
      out.write("				");

				User user1 = (User) session.getAttribute("user");
				if (user1 == null) {
				
      out.write("\r\n");
      out.write("				<a href=\"login.jsp\"\r\n");
      out.write("					class=\"bg-red-500 px-3 py-1 rounded-lg hover:bg-red-600\">Login</a>\r\n");
      out.write("				<a href=\"register.jsp\"\r\n");
      out.write("					class=\"bg-green-500 px-3 py-1 rounded-lg hover:bg-green-600\">Register</a>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<a id=\"logout\" href=\"#!\"\r\n");
      out.write("					class=\"bg-red-500 px-3 py-1 rounded-lg hover:bg-red-600\">Logout</a>\r\n");
      out.write("				<a href=\"#!\"\r\n");
      out.write("					class=\"bg-green-500 px-3 py-1 rounded-lg hover:bg-green-600\">");
      out.print(user1.getName());
      out.write("</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Script for Mobile Menu -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$('#logout').on('click', function (event) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("    $('#logout').html(\"<i class='fa fa-spinner fa-spin'></i>\");\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '");
      out.print( request.getContextPath() );
      out.write("/Logout', // dynamic path\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            if (data.trim() === \"true\") {\r\n");
      out.write("                alert(\"Logout Successfully!\");\r\n");
      out.write("                window.location.href = \"index.jsp\";\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"Server response: \" + data);\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error: function (xhr, status, error) {\r\n");
      out.write("            $('#submitBtn').text(\"Logout\");\r\n");
      out.write("\r\n");
      out.write("            alert(\"Something went wrong! \" + status + \" - \" + error);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	");

	User u3 = (User) session.getAttribute("user");
	int userId = u3 != null ? u3.getUserId() : 0;
	
      out.write("\r\n");
      out.write("	<div class=\"max-w-6xl mx-auto p-6 mb-2\">\r\n");
      out.write("		<h1\r\n");
      out.write("			class=\"text-3xl font-extrabold mb-6 text-center text-blue-700 tracking-wide\">\r\n");
      out.write("			My Contacts</h1>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overflow-hidden bg-white shadow-lg rounded-xl\">\r\n");
      out.write("			<table\r\n");
      out.write("				class=\"min-w-full border border-gray-200 divide-y divide-gray-200\">\r\n");
      out.write("				<thead\r\n");
      out.write("					class=\"bg-gradient-to-r from-blue-600 to-indigo-600 text-white\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Name</th>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Phone</th>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Email</th>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Address</th>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Notes</th>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Added\r\n");
      out.write("							Date</th>\r\n");
      out.write("						<th class=\"px-6 py-3 text-left font-semibold uppercase\">Action</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody class=\"divide-y divide-gray-100\">\r\n");
      out.write("					");

					List<Contact> l = (List<Contact>) ContactLists.getListByUserId(userId);
					if (l != null && !l.isEmpty()) {
						for (Contact c : l) {
					
      out.write("\r\n");
      out.write("					<tr class=\"hover:bg-blue-50 transition\">\r\n");
      out.write("						<td id=\"name\" class=\"px-6 py-4 font-medium text-gray-900\">");
      out.print(c.getName());
      out.write("</td>\r\n");
      out.write("						<td id=\"phone\" class=\"px-6 py-4 text-gray-700\">");
      out.print(c.getPhone());
      out.write("</td>\r\n");
      out.write("						<td id=\"email\" class=\"px-6 py-4 text-gray-700\">");
      out.print(c.getEmail());
      out.write("</td>\r\n");
      out.write("						<td id=\"address\" class=\"px-6 py-4 text-gray-700\">");
      out.print(c.getAddress());
      out.write("</td>\r\n");
      out.write("						<td id=\"notes\" class=\"px-6 py-4 text-gray-700\">");
      out.print(c.getNotes());
      out.write("</td>\r\n");
      out.write("						<td class=\"px-6 py-4 text-gray-500 text-sm\">");
      out.print(c.getCreatedAt().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));
      out.write("</td>\r\n");
      out.write("						<td class=\"px-6 py-4 text-gray-500 text-sm flex space-x-2\">\r\n");
      out.write("							<button onclick=\"onEdit(this)\" \r\n");
      out.write("								data-id=\"");
      out.print(c.getContactId());
      out.write("\"\r\n");
      out.write("							    data-name=\"");
      out.print(c.getName());
      out.write("\"\r\n");
      out.write("							    data-phone=\"");
      out.print(c.getPhone());
      out.write("\"\r\n");
      out.write("							    data-email=\"");
      out.print(c.getEmail());
      out.write("\"\r\n");
      out.write("							    data-address=\"");
      out.print(c.getAddress());
      out.write("\"\r\n");
      out.write("							    data-notes=\"");
      out.print(c.getNotes());
      out.write("\"\r\n");
      out.write("							        class=\"bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded\">\r\n");
      out.write("							    Edit\r\n");
      out.write("							</button>\r\n");
      out.write("							<button onclick=\"onDelete('");
      out.print(c.getContactId());
      out.write("', this, event)\"\r\n");
      out.write("								class=\"bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded\">\r\n");
      out.write("								Delete</button>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					}
					} else {
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"6\" class=\"px-6 py-6 text-center text-gray-500 italic\">\r\n");
      out.write("							No contacts found</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Edit Contact Modal -->\r\n");
      out.write("	<div id=\"editModal\"\r\n");
      out.write("		class=\"fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center hidden\">\r\n");
      out.write("		<div class=\"bg-white rounded-xl w-1/3 p-6 relative\">\r\n");
      out.write("			<h2 class=\"text-2xl font-bold mb-4 text-center text-blue-700\">Edit\r\n");
      out.write("				Contact</h2>\r\n");
      out.write("			<form id=\"editForm\">\r\n");
      out.write("				<input type=\"hidden\" id=\"editContactId\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label class=\"block mb-1 font-semibold\">Name</label> <input\r\n");
      out.write("						type=\"text\" id=\"editName\"\r\n");
      out.write("						class=\"w-full border border-gray-300 rounded px-3 py-2\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label class=\"block mb-1 font-semibold\">Phone</label> <input\r\n");
      out.write("						type=\"text\" id=\"editPhone\"\r\n");
      out.write("						class=\"w-full border border-gray-300 rounded px-3 py-2\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label class=\"block mb-1 font-semibold\">Email</label> <input\r\n");
      out.write("						type=\"email\" id=\"editEmail\"\r\n");
      out.write("						class=\"w-full border border-gray-300 rounded px-3 py-2\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label class=\"block mb-1 font-semibold\">Address</label> <input\r\n");
      out.write("						type=\"text\" id=\"editAddress\"\r\n");
      out.write("						class=\"w-full border border-gray-300 rounded px-3 py-2\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<label class=\"block mb-1 font-semibold\">Notes</label>\r\n");
      out.write("					<textarea id=\"editNotes\"\r\n");
      out.write("						class=\"w-full border border-gray-300 rounded px-3 py-2\"></textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"flex justify-end space-x-2\">\r\n");
      out.write("					<button type=\"button\" onclick=\"closeEditModal()\"\r\n");
      out.write("						class=\"bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded\">Cancel</button>\r\n");
      out.write("					<button id=\"editSubmitBtn\" type=\"submit\"\r\n");
      out.write("						class=\"bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded\">Save</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<button onclick=\"closeEditModal()\"\r\n");
      out.write("				class=\"absolute top-2 right-2 text-gray-500 hover:text-gray-700 text-xl\">&times;</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-gray-900 text-gray-300\">\r\n");
      out.write("  <div class=\"max-w-7xl mx-auto px-4 py-8 md:flex md:items-center md:justify-between\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Left Side -->\r\n");
      out.write("    <div class=\"text-center md:text-left mb-4 md:mb-0\">\r\n");
      out.write("      <h2 class=\"text-lg font-semibold\">Contact Management System</h2>\r\n");
      out.write("      <p class=\"text-sm text-gray-400\">Manage your contacts securely & easily.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right Side Links -->\r\n");
      out.write("    <div class=\"flex justify-center space-x-6\">\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Contact List</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Add Contact</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Edit Contact</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Login</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Register</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bottom Line -->\r\n");
      out.write("  <div class=\"border-t border-gray-700 text-center py-4 text-sm text-gray-400\">\r\n");
      out.write("    Â© 2025 Contact Management System. All rights reserved. <br>\r\n");
      out.write("    Design by Tauseef Khan\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	function onDelete(contactId, btn, event){\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    $(btn).html(\"<i class='fa fa-spinner fa-spin'></i>\");\r\n");
      out.write("	    \r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	        url: '");
      out.print(request.getContextPath());
      out.write("/ContactDelete',\r\n");
      out.write("				type : 'POST',\r\n");
      out.write("				data : {\r\n");
      out.write("					contactId : contactId\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					if (data.trim() == \"true\") {\r\n");
      out.write("						alert(\"Contact Deleted!\");\r\n");
      out.write("						$(btn).text(\"Delete\");\r\n");
      out.write("						window.location.href = \"contactList.jsp\";\r\n");
      out.write("					} else {\r\n");
      out.write("						$(btn).text(\"Delete\");\r\n");
      out.write("						alert(\"Contact not deleted!\");\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					$(btn).text(\"Delete\");\r\n");
      out.write("					alert(\"Something went wrong\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function onEdit(btn) {\r\n");
      out.write("			let contactId=$(btn).data('id')\r\n");
      out.write("			let name=$(btn).data('name')\r\n");
      out.write("			let phone=$(btn).data('phone')\r\n");
      out.write("			let email=$(btn).data('email')\r\n");
      out.write("			let address=$(btn).data('address')\r\n");
      out.write("			let notes=$(btn).data('notes')\r\n");
      out.write("			$('#editContactId').val(contactId);\r\n");
      out.write("		    $('#editName').val(name);\r\n");
      out.write("		    $('#editPhone').val(phone);\r\n");
      out.write("		    $('#editEmail').val(email);\r\n");
      out.write("		    $('#editAddress').val(address);\r\n");
      out.write("		    $('#editNotes').val(notes);\r\n");
      out.write("\r\n");
      out.write("			$(\"#editModal\").removeClass(\"hidden\");\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function closeEditModal() {\r\n");
      out.write("		    $(\"#editModal\").addClass(\"hidden\");\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$('#editForm').on('submit',function(event){\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			let contactId=$('#editContactId').val();;\r\n");
      out.write("			let userId=");
      out.print(userId);
      out.write(";\r\n");
      out.write("			let name=$('#editName').val();\r\n");
      out.write("			let phone=$('#editPhone').val();\r\n");
      out.write("			let email=$('#editEmail').val();\r\n");
      out.write("			let address=$('#editAddress').val();\r\n");
      out.write("			let notes=$('#editNotes').val();\r\n");
      out.write("		    \r\n");
      out.write("			const d={\r\n");
      out.write("				contactId:contactId,\r\n");
      out.write("				userId:userId,\r\n");
      out.write("				name:name,\r\n");
      out.write("				phone:phone,\r\n");
      out.write("				email:email,\r\n");
      out.write("				address:address,\r\n");
      out.write("				notes:notes\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$('#editSubmitBtn').html(\"<i class='fa fa-spinner fa-spin'></i>\");\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:'");
      out.print(request.getContextPath());
      out.write("/EditContacts',\r\n");
      out.write("				type:\"POST\",\r\n");
      out.write("				data:d,\r\n");
      out.write("				success:function(data){\r\n");
      out.write("					if(data.trim()==\"true\"){\r\n");
      out.write("						alert(\"Contact Updated!\");\r\n");
      out.write("						window.location.href = \"contactList.jsp\";\r\n");
      out.write("						$('#editSubmitBtn').text(\"Save\");\r\n");
      out.write("					}else{\r\n");
      out.write("						$('#editSubmitBtn').text(\"Save\");\r\n");
      out.write("						alert(\"Contact not Updated!\");\r\n");
      out.write("					}\r\n");
      out.write("				},error:function(){\r\n");
      out.write("					$('#editSubmitBtn').text(\"Save\");\r\n");
      out.write("					alert(\"Something went wrong!\");\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
