/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-09-02 11:14:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entities.User;
import com.entities.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1756810594956L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1756731695891L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.entities.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Contact Management System || Home page</title>\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<nav class=\"bg-blue-600 text-white shadow-lg\">\r\n");
      out.write("	<div class=\"max-w-7xl mx-auto px-4\">\r\n");
      out.write("		<div class=\"flex justify-between h-16\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Logo / Brand -->\r\n");
      out.write("			<div class=\"flex items-center\">\r\n");
      out.write("				<a href=\"/ContactManagementSystem\"\r\n");
      out.write("					class=\"text-xl font-bold tracking-wide\">Contact Mangement\r\n");
      out.write("					System</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Links -->\r\n");
      out.write("			<div class=\"hidden md:flex items-center space-x-6\">\r\n");
      out.write("				<a href=\"contactList.jsp\" class=\"hover:text-gray-200\">Contact\r\n");
      out.write("					List</a> <a href=\"AddContact.jsp\" class=\"hover:text-gray-200\">Add\r\n");
      out.write("					Contact</a>\r\n");
      out.write("				");

				User user1 = (User) session.getAttribute("user");
				if (user1 == null) {
				
      out.write("\r\n");
      out.write("				<a href=\"login.jsp\"\r\n");
      out.write("					class=\"bg-red-500 px-3 py-1 rounded-lg hover:bg-red-600\">Login</a>\r\n");
      out.write("				<a href=\"register.jsp\"\r\n");
      out.write("					class=\"bg-green-500 px-3 py-1 rounded-lg hover:bg-green-600\">Register</a>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<a id=\"logout\" href=\"#!\"\r\n");
      out.write("					class=\"bg-red-500 px-3 py-1 rounded-lg hover:bg-red-600\">Logout</a>\r\n");
      out.write("				<a href=\"#!\"\r\n");
      out.write("					class=\"bg-green-500 px-3 py-1 rounded-lg hover:bg-green-600\">");
      out.print(user1.getName());
      out.write("</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Script for Mobile Menu -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$('#logout').on('click', function (event) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("    $('#logout').html(\"<i class='fa fa-spinner fa-spin'></i>\");\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: '");
      out.print( request.getContextPath() );
      out.write("/Logout', // dynamic path\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            if (data.trim() === \"true\") {\r\n");
      out.write("                alert(\"Logout Successfully!\");\r\n");
      out.write("                window.location.href = \"index.jsp\";\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"Server response: \" + data);\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error: function (xhr, status, error) {\r\n");
      out.write("            $('#submitBtn').text(\"Logout\");\r\n");
      out.write("\r\n");
      out.write("            alert(\"Something went wrong! \" + status + \" - \" + error);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"h-screen bg-gradient-to-r from-blue-500 via-purple-600 to-pink-500 flex items-center justify-center\">\r\n");
      out.write("		<div class=\"text-center text-white px-6\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Title -->\r\n");
      out.write("			<h1 class=\"text-5xl font-extrabold mb-4 drop-shadow-lg\">📒\r\n");
      out.write("				Contact Management System</h1>\r\n");
      out.write("\r\n");
      out.write("			<!-- Subtitle -->\r\n");
      out.write("			<p class=\"text-lg mb-8 max-w-xl mx-auto\">Manage all your contacts\r\n");
      out.write("				in one place — secure, simple, and fast. Add, edit, search, and\r\n");
      out.write("				organize your contacts with ease.</p>\r\n");
      out.write("\r\n");
      out.write("			<!-- Buttons -->\r\n");
      out.write("			<div class=\"space-x-4\">\r\n");
      out.write("				");

				User user=(User)session.getAttribute("user");
				if(user==null){
				
      out.write("\r\n");
      out.write("				<a href=\"login.jsp\"\r\n");
      out.write("					class=\"bg-white text-blue-600 font-semibold px-6 py-2 rounded-lg shadow-md hover:bg-gray-200 transition\">\r\n");
      out.write("					Login </a> <a href=\"register.jsp\"\r\n");
      out.write("					class=\"bg-yellow-400 text-gray-900 font-semibold px-6 py-2 rounded-lg shadow-md hover:bg-yellow-300 transition\">\r\n");
      out.write("					Register </a>\r\n");
      out.write("				");
}else{ 
      out.write("\r\n");
      out.write("					<a href=\"#!\"\r\n");
      out.write("					class=\"bg-white text-blue-600 font-semibold px-6 py-2 rounded-lg shadow-md hover:bg-gray-200 transition\">\r\n");
      out.write("					Start you journey with us </a> <a href=\"AddContact.jsp\"\r\n");
      out.write("					class=\"bg-yellow-400 text-gray-900 font-semibold px-6 py-2 rounded-lg shadow-md hover:bg-yellow-300 transition\">\r\n");
      out.write("					Add Contacts </a>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("	  ");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-gray-900 text-gray-300\">\r\n");
      out.write("  <div class=\"max-w-7xl mx-auto px-4 py-8 md:flex md:items-center md:justify-between\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Left Side -->\r\n");
      out.write("    <div class=\"text-center md:text-left mb-4 md:mb-0\">\r\n");
      out.write("      <h2 class=\"text-lg font-semibold\">Contact Management System</h2>\r\n");
      out.write("      <p class=\"text-sm text-gray-400\">Manage your contacts securely & easily.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right Side Links -->\r\n");
      out.write("    <div class=\"flex justify-center space-x-6\">\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Contact List</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Add Contact</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Edit Contact</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Login</a>\r\n");
      out.write("      <a href=\"#!\" class=\"hover:text-white\">Register</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bottom Line -->\r\n");
      out.write("  <div class=\"border-t border-gray-700 text-center py-4 text-sm text-gray-400\">\r\n");
      out.write("    Â© 2025 Contact Management System. All rights reserved. <br>\r\n");
      out.write("    Design by Tauseef Khan\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
